apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp-namespace
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5001              # Puerto accesible externamente
      targetPort: 5001         # Puerto dentro del contenedor
  type: LoadBalancer              # Usa LoadBalancer si quieres acceso externo
