apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend
          image: dcruz06/frontend:v1 # Imagen con Flask + Angular
          ports:
            - containerPort: 4200  # Puerto del servidor Flask
