apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: myapp-namespace
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 4200             # Puerto donde el servicio estará disponible para el exterior
      targetPort: 4200      # Puerto en el contenedor Angular
  type: LoadBalancer        # Para hacer accesible el frontend externamente
