apiVersion: v1
kind: Namespace
metadata:
  name: myapp-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: myapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: dcruz06/db:latest
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
