apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: myapp-namespace
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432         # Puerto expuesto
      targetPort: 5432    # Puerto en el contenedor
  type: LoadBalancer      # Cambia de ClusterIP a LoadBalancer