apiVersion: v1
kind: Namespace
metadata:
  name: myapp-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: myapp-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#Este manifiesto asegura que los datos en la base de datos se mantendrán incluso si el pod se reinicia.